# Generated by Django 5.0.7 on 2024-07-23 13:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampagneMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCampagne', models.CharField(max_length=50)),
                ('objectif', models.TextField(max_length=100)),
                ('date_debut', models.DateField(default=datetime.date(2024, 7, 23))),
                ('date_fin', models.DateField(default=datetime.date(2024, 7, 23), null=True)),
                ('document', models.FileField(null=True, upload_to='')),
                ('media', models.ImageField(null=True, upload_to='')),
                ('video', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCategory', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, null=True)),
                ('telephone', models.CharField(default='+237678963685', max_length=30, null=True)),
                ('address', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, null=True)),
                ('telephone', models.CharField(default='+237678963685', max_length=30, null=True)),
                ('address', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, null=True)),
                ('telephone', models.CharField(default='+237678963685', max_length=30, null=True)),
                ('address', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('date_ajout', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_fin', models.DateField(default=datetime.date.today)),
                ('statut', models.CharField(choices=[('Nouveau', 'Nouveau'), ('Encour', 'En cours de traitement'), ('Annule', 'Annulé'), ('Valide', 'Validé')], default='Nouveau', max_length=30, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.client')),
                ('paniers', models.ManyToManyField(related_name='commandes', to='cms.lignecommande')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomProduit', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100, null=True)),
                ('quantite', models.IntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.category')),
            ],
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.produit'),
        ),
        migrations.CreateModel(
            name='ServiceClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateField(default=datetime.date(2024, 7, 23))),
                ('problemeSignale', models.TextField(max_length=50)),
                ('statut', models.CharField(choices=[('Nouveau', 'Nouveau'), ('Encour', 'Encour de traitement'), ('Refuse', 'Refusé'), ('Regle', 'Reglé'), ('Ferme', 'Fermé')], default='Nouveau', max_length=30, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.client')),
                ('gestionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.gestionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_fin', models.DateField()),
                ('total_prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_quantite', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.client')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cms.commande')),
                ('paniers', models.ManyToManyField(related_name='ventes', to='cms.lignecommande')),
            ],
        ),
    ]
