# Generated by Django 5.0.7 on 2024-07-23 15:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2024, 7, 23))),
                ('objet', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('emailFrom', models.TextField(default="'nahangmercytangham@gmail.com'")),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='cms.client')),
            ],
        ),
    ]
