# Generated by Django 5.0.6 on 2024-06-19 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('telephone', models.CharField(default='+237678963685', max_length=30)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='commande',
            name='total',
        ),
        migrations.AddField(
            model_name='campagnemarketing',
            name='document',
            field=models.FileField(default='/media/document.pdf', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='campagnemarketing',
            name='media',
            field=models.ImageField(default='/media/document.pdf', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='campagnemarketing',
            name='video',
            field=models.FileField(default='/media/document.pdf', upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='commande',
            name='produit',
            field=models.ManyToManyField(to='cms.produit'),
        ),
        migrations.AddField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('Nouveau', 'Nouveau'), ('Encour', 'Encour de traitement'), ('Annule', 'Annulé'), ('Valide', 'Validé')], default='Nouveau', max_length=30),
        ),
        migrations.AlterField(
            model_name='serviceclient',
            name='statut',
            field=models.CharField(choices=[('Nouveau', 'Nouveau'), ('Encour', 'Encour de traitement'), ('Refuse', 'Refusé'), ('Regle', 'Reglé'), ('Ferme', 'Fermé')], default='Nouveau', max_length=30),
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vente', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.clientprospect')),
                ('idCommande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.commande')),
                ('produit', models.ManyToManyField(to='cms.produit')),
            ],
        ),
    ]
