# Generated by Django 5.0.6 on 2024-06-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_client_remove_commande_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagnemarketing',
            name='media',
            field=models.ImageField(default='/media/img.jpeg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='campagnemarketing',
            name='video',
            field=models.FileField(default='/media/video.mp3', upload_to='videos/'),
        ),
    ]
