# Generated by Django 5.0.7 on 2024-07-24 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagnemarketing',
            name='date_debut',
            field=models.DateField(default=datetime.date(2024, 7, 24)),
        ),
        migrations.AlterField(
            model_name='campagnemarketing',
            name='date_fin',
            field=models.DateField(default=datetime.date(2024, 7, 24), null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='date',
            field=models.DateField(default=datetime.date(2024, 7, 24)),
        ),
        migrations.AlterField(
            model_name='serviceclient',
            name='date_demande',
            field=models.DateField(default=datetime.date(2024, 7, 24)),
        ),
    ]
